# Generated by Selenium IDE
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from testAutomation import PythonOrgSearch

class TestHannibal(unittest.TestCase):
  
  def setUp(self):
    self.driver = webdriver.Chrome()
    
  def test_hannibal(self):
    self.driver.get("https://www.wikipedia.org/")
    self.driver.find_element(By.ID, "searchInput").click()
    self.driver.find_element(By.ID, "searchInput").send_keys("hannibal")
    PythonOrgSearch.test_search_in_python_org

  def tearDown(self):
        self.driver.close()

if __name__ == "__main__":
    unittest.main()
  
