version: 2
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run: sudo pip install selenium
      - run: sudo pip install requests
      - run: 
          command: python testAutomation.py
                   python testHannibal.py